# Generated by Django 3.0.7 on 2020-06-07 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200607_0729'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.TextField(blank=True),
        ),
    ]
