# Generated by Django 3.0.7 on 2020-06-07 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20200607_0729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='title',
            new_name='subject',
        ),
    ]
